/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SrvrRouteImport } from './routes/srvr'
import { Route as IndexRouteImport } from './routes/index'

const SrvrRoute = SrvrRouteImport.update({
  id: '/srvr',
  path: '/srvr',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/srvr': typeof SrvrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/srvr': typeof SrvrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/srvr': typeof SrvrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/srvr'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/srvr'
  id: '__root__' | '/' | '/srvr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SrvrRoute: typeof SrvrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/srvr': {
      id: '/srvr'
      path: '/srvr'
      fullPath: '/srvr'
      preLoaderRoute: typeof SrvrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SrvrRoute: SrvrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
